### PR TITLE
Added a basic how to/getting started guide

### PR DESCRIPTION
**Pull request by jaikoo**

### CODE REVIEW

**Comment by marcincichon** [comment]
@jaikoo there are few more things I can think of:
- setting up *AMP (e.g. MySQL ins't preinstalled on OSX)
- enabling mod rewrite
- setting up the site locally under http://mojintranet/ (as of now the url is hardcoded in Gruntfile so it's a must have)

**Comment by sparkdevelopment** [comment]
Shoudl we change "A recent version of Wordpress" to "The most recent public release of WordPress" and provide a link to wordpress.org/latest?

**Comment by sparkdevelopment** [comment]
Currently there is a little bit of a disconnect between the theme and the custom post types we have because we're using Pods. I plan to move the CPT definition into the theme so we won't need Pods, but at the moment some things (for now, news, but eventually events/webchats and possibly more) will not work without Pods being installed and a definition of those CPTs being loaded into Pods (a database import will do this, but no good if a 3rd party is looking to reuse the theme).

**Comment by sparkdevelopment** [comment]
Also, without the Document Revisions plugin, existing documents _may_ not work. For a new installation this won't be an issue. However, is it worth including a list of recommended plugins?

**Comment by marcincichon** [comment]
@sparkdevelopment good point about the plugins. In my experience, Pods, Document Revisions and Relevanssi Premium all all required for front end work

**Comment by jaikoo** [comment]
@marcincichon and @sparkdevelopment thanks guys, I'll add these details to the readme.

**Comment by marcincichon** [comment]
@jaikoo thx Jon. All looks good to me

**Pull request merged**
