### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by marcincichon**
@ollietreend @RobertWDLowe can you review? thanks
Changes:
- fix for the notice error on widgets API that we get with the new DB
- jQuery version is now controlled by F/E instead of using the one supplied by WP
- wp_footer is now loaded in the same way as the wp_head (pregenerated and stored on the MVC object)
- Google Tag Manager ID is now a constant which can be defined in wp config

### CODE REVIEW

**Comment by RobertWDLowe** [comment]
Hi Marcin,

Rather then adding the new jquery file directly into the head it would be better to enqueue the new jquery file using the below function. You can put this straight after the deregister.  Set the handle to 'jquery'

wp_enqueue_script

**Comment by marcincichon** [comment]
@RobertWDLowe There are absolutely no benefits of doing that for us as we control the theme. I'd gladly replace all remaining bits added by WP if I only had time to do that.

**Comment by RobertWDLowe** [comment]
@marcincichon though the theme may not need this. Should any of the plugins we use now or in the future use the default dependency functionality provided by wordpress to check for 'jquery' before they including their own scripts they will not work.

**Comment by marcincichon** [comment]
@RobertWDLowe Sure, I'm aware of that. We're not using any plugins on the front end, as like I said, we have the full control of the code. No contamination ;)

**Comment by marcincichon** [comment]
@ollietreend Sure, if we ever use any plugin like that I'd be happy to enqueue this script. Until then I'd rather keep the code as clean and as easy to understand as possible for any future non-WP devs to work on the project.

**Pull request closed without merging**
